gitalk:
  enable: true  #启用gitalk
  github_id: moakap  #github帐号 例：CodeHaotian
  id: location.pathname  #此设置参照下文常见问题说明
  repo: https://github.com/moakap/lovcomments.git  #存放评论的仓库名称
  client_id: 11f478f6fbb7f83b209b #application的id，即上文Client ID
  client_secret: 3b840f0ae72266ae9bc8f5a498b47a28cd5bfe5d #application的密码，即上文Client Secret
  admin_user: moakap #页面显示联系**初始化评论 例：CodeHaotian
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN
