name: Deploy Hexo Blog to Server

on:
  push:
    branches: [main]  # 或你使用的分支名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Hexo
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate static files
        run: hexo generate

      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "public/*"
          target: ${{ secrets.DEPLOY_PATH }}
